import Head from 'next/head';
import Image from 'next/image';
import Card from '../components/Card';
import Banner from '../components/Banner';
import styles from '../styles/Home.module.css';

export default function Home() {
	const handleOnBannerBtnClick = () => {
		console.log('hi, banner button');
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>next_coffee</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Banner
					buttonText='View store nearby'
					handleOnClick={handleOnBannerBtnClick}
				/>
				<div className={styles.heroImage}>
					<Image src='/hero.png' width={450} height={300} />
				</div>
				<div className={styles.cardLayout}>
					<Card
						className={styles.card}
						name={'Darkhorse Coffee'}
						imgUrl='/hero2.png'
						href='/coffee-store/darkhorse-coffee'
					/>
					<Card
						className={styles.card}
						name={'Darkhorse Coffee'}
						imgUrl='/hero2.png'
						href='/coffee-store/darkhorse-coffee'
					/>
				</div>
			</main>
		</div>
	);
}
